bundled_packages_dir: packages
data_dir: data
description: Some test description
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  example_model_input: {"a": "b", "c": True}
  pretty_name: Baseten Test Model
  avatar_url: https://cdn.baseten.co/production/static/logos/baseten-new-logo.svg
  cover_image_url: https://cdn.baseten.co/production/static/logos/baseten-new-logo.svg
  tags:
  - text-generation
model_module_dir: model
model_name: "Baseten Test Model"
model_type: custom
python_version: py39
requirements: []
resources:
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets:
  super_secret: default_super_secret
spec_version: '2.0'
system_packages: []