bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  pretty_name: Baseten Test Model
  tags:
  - text-generation
model_module_dir: model
model_name: null
model_type: custom
python_version: py39
requirements: []
resources:
  cpu: 500m
  memory: 512Mi
  use_gpu: false
secrets:
  super_secret: default_super_secret
spec_version: '2.0'
system_packages: []
external_data:
  - url: https://s3.console.aws.amazon.com/s3/object/baseten-public-models-test?region=us-west-2&prefix=dvc/09/c6ad50c89497979e7dc6ea1d00887e
    backend: http_public
    local_data_path: test_blob
train:
  resources:
    cpu: 500m
    memory: 512Mi
    use_gpu: false
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables:
    key1: default
    key2: -1
    key3:
      nested: default
      listVal:
        - -1
